trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
steps:
- task: Docker@2
  displayName: Login to Harbor
  inputs:
    command: login
    containerRegistry: hubrepo3
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: demo.goharbor.io/nodejs
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile