trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'nodejs'
steps:
- task: Docker@2
  displayName: Login to Harbor
  inputs:
    command: login
    containerRegistry: hubrepo3
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile
- script: docker tag nodejs demo.goharbor.io/nodejs/repository:14.04 
- script: docker push demo.goharbor.io/nodejs/repository:14.04 