trigger:
- main
pool:
 vmImage: 'ubuntu-18.04'
steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: nodejs/repository:14.04
    dockerfile: Dockerfile
    containerRegistry: hubrepo3
    tags: $(tag)