trigger:
- main
pool:
 vmImage: 'ubuntu-18.04'
variables:
 imageName: 'demo.goharbor.io/nodejs/repository:14.04'
steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: Dockerfile
    containerRegistry: hubrepo3