trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'nodejs'
steps:
- task: Docker@2
  displayName: Login to Harbor
  inputs:
    command: login
    containerRegistry: hubrepo3
- task: Docker@2
  displayName: Build an image
  inputs:
    command: buildAndPush
    repository: nodejs/repository:$(tag)
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile