trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'demo.goharbor.io/nodejs/repository:14.04'
steps:
- task: Docker@2
  displayName: Login to Harbor
  inputs:
    command: login
    containerRegistry: hubrepo3
- task: Docker@2
  displayName: Build an image
  inputs:
    command: buildAndPush
    repository: $(imageName)
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile