trigger:
- main
pool:
 vmImage: 'ubuntu-18.04'
variables:
 imageName: 'pipelines-javascript-docker'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    dockerfile: $(dockerfilePath)
- task: Docker@2
  displayName: Push image
  inputs:
    command: push
    repository: $(imageRepository)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      test1
      test2