trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'nodejs'
steps:
- task: Docker@2
  displayName: Login to Harbor
  inputs:
    command: login
    containerRegistry: hubrepo3
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile
- script: docker login https://hub.docker.com --username=albertoraaz --password=Ven320wl8ven!
- script: docker push nodejsproject