trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'nodejs:$(Build.BuildId)'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile