trigger:
- main
pool:
  vmImage: 'ubuntu-18.04'
  variables:
  imageName: 'nodejs'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    repository: nodejs/repository
    containerRegistry: hubrepo3
    Dockerfile: Dockerfile
    tags: $(build.buildId)
- task: Docker@2
  displayName: Push Image
- script: docker login demo.goharbor.io/ --username=albertoraaz --password=Ven320wl8ven!
- script: docker push demo.goharbor.io/nodejs/repository:$(build.buildId) 